apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: messenger-prod

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/part-of: messenger

# Фиксируем версии образов вместо latest
images:
  - name: mablinov2704/frontend
    newTag: v1.0.0
  - name: mablinov2704/bff
    newTag: v1.0.0
  - name: mablinov2704/user-service
    newTag: v1.0.0
  - name: mablinov2704/message-service
    newTag: v1.0.0

patches:
  - path: affinity-postgres.yaml
    target:
      kind: Deployment
      name: postgres
  - path: affinity-app-services.yaml
    target:
      kind: Deployment
      name: user-service
  - path: affinity-message-service.yaml
    target:
      kind: Deployment
      name: message-service
  - path: affinity-app-services.yaml
    target:
      kind: Deployment
      name: bff
  - path: affinity-app-services.yaml
    target:
      kind: Deployment
      name: frontend
  - path: replicas.yaml
  - path: resources.yaml