apiVersion: batch/v1
kind: Job
metadata:
  name: migrate-messages
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migrate-messages
          image: ghcr.io/kukymbr/goose-docker:latest
          env:
            - name: GOOSE_DRIVER
              value: postgres
            - name: GOOSE_DBSTRING
              valueFrom:
                secretKeyRef:
                  name: messager-db-secret
                  key: MSG_DB_DSN
            - name: GOOSE_MIGRATION_DIR
              value: /migrations
          volumeMounts:
            - name: migrations
              mountPath: /migrations
      volumes:
        - name: migrations
          configMap:
            name: messages-migrations
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: messages-migrations
data:
  001_create_messages_table.sql: |
    -- +goose Up
    CREATE TABLE IF NOT EXISTS messages (
        id SERIAL PRIMARY KEY,
        user_id INTEGER NOT NULL,
        content TEXT NOT NULL,
        file_url TEXT,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );
    
    CREATE INDEX idx_messages_user_id ON messages(user_id);
    
    -- +goose Down
    DROP TABLE IF EXISTS messages;
