apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: messager-dev

resources:
  - ../../base
  - minio.yaml
  - s3-pv.yaml

images:
  - name: mablinov2704/frontend
    newTag: latest
  - name: mablinov2704/bff
    newTag: latest
  - name: mablinov2704/user-service
    newTag: latest
  - name: mablinov2704/message-service
    newTag: latest